apiVersion: dash.plural.sh/v1alpha1
kind: DashApplication
metadata:
  name: picsum
  namespace: dash
spec:
  replicas: 1
  container:
    image: "zreigz/dash-picsum:0.1.0"
    containerPort: 8050
  ingress:
    ingressClassName: "nginx"
    path: "/picsum"