---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dash-controller
  namespace: dash
  finalizers:
    - pluralsh.dash-controller/deployment-protection
  annotations:
    config.kubernetes.io/depends-on: dash.plural.sh/namespaces/dash/DashApplication/picsum,dash.plural.sh/namespaces/dash/DashApplication/cytoscape,dash.plural.sh/namespaces/dash/DashApplication/echo
  labels:
    dash.plural.sh/name: dash-controller
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      dash.plural.sh/name: dash-controller
  template:
    metadata:
      labels:
        dash.plural.sh/name: dash-controller
    spec:
      serviceAccountName: dash-controller-sa
      containers:
        - name: dash-controller
          image: ghcr.io/pluralsh/dash-controller:0.0.8
          imagePullPolicy: Always
