---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dash-controller-role
  namespace: default
  labels:
    plural.sh/name: dash-controller
rules:
- apiGroups: ["dash.plural.sh"]
  resources: ["dashapplications", "dashapplications/status"]
  verbs: ["get", "list", "watch", "update", "create", "delete", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["deployments", "services"]
  verbs: ["get", "list", "watch", "update", "create", "delete", "patch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dash-controller
  namespace: default
  labels:
    plural.sh/name: dash-controller
subjects:
  - kind: ServiceAccount
    name: dash-controller-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: dash-controller-role
  apiGroup: rbac.authorization.k8s.io
